- name: Upload coverage to Coveralls
  uses: coverallsapp/github-action@v2
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    parallel: true
